export const CONNECT_WALLET_DATA = "CONNECT_WALLET_DATA";
export const CONNECT_WALLET_ERROR = "CONNECT_WALLET_ERROR";

export const DISCONNECT_WALLET_DATA = "DISCONNECT_WALLET_DATA";
export const DISCONNECT_WALLET_ERROR = "DISCONNECT_WALLET_ERROR";

export const GET_MY_BALANCE_DATA="GET_MY_BALANCE_DATA"
export const GET_MY_BALANCE_ERROR="GET_MY_BALANCE_ERROR"
export const GET_MY_BALANCE_LOADING_BUTTON="GET_MY_BALANCE_LOADING_BUTTON"

export const WALLET_ACCOUNT_DATA = "WALLET_ACCOUNT_DATA";